from .integrate import *
from .gated_integrate import *
from .regression import *
from .cuecombination import *
from .interval import *
from .mnist import *
from .recurrent_teacher import *
from .recurrent_regression import *
from .sequence_classification import *
from .classification import *
from .randman import *
from .base import *
from .gaussian_teacher import *
from .spheres import *
